<div class="dashboard-user row">
	<div class="page-title col-xs-12">
		<h1>Users</h1>
	</div>
	<div class="user-list col-xs-12">
		<div class="table-responsive">
			<table class="table">
				<thead>
					<th>Login</th>
					<th>Email</th>
					<th>Registered on</th>
					<th>Last connection</th>
					<th>Rights</th>
					<th>Set ban</th>
					<th></th>
					<th></th>
				</thead>
				<tbody>
					<?php require('controllers/content/dashboard_user.php') ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
