<hr/>
<h3>Créer une section</h3>
<form method="post" action="?page=home" role="form">
	<div class="form-group">
		<label for="name" class="form-control">Nom</label>
		<input type="text" name="name" value="<?=htmlentities($name)?>" placeholder="31 caractères max." id="name">
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<textarea name="description" placeholder="511 caractères max." id="description" class="form-control"><?=htmlentities($description)?></textarea>
	</div>
	<div class="form-group">
		<label for="image">Image</label>
		<input type="url" name="image" placeholder="200x200, 25Ko max." id="image" class="form-control">
	</div>
	<button type="submit" class="btn btn-primary pull-right">Créer</button>
</form>
