<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="?page=home">Forum</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<div class="nav navbar-nav">
				<ol class="breadcrumb">
					<?php require('controllers/menu_list.php') ?>
				</ol>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<?php if(!isset($_SESSION['id'])) {?>
				<li><a href="?page=login">Login</a></li>
				<li><a href="?page=register">Register</a></li>
				<?php } else { ?>
				<?php if(($currentUser -> getStatus()) > 0) { ?>
				<li><a href="?page=dashboard">Dashboard</a></li>
				<?php } ?>
				<li><a href="?page=user&amp;id=<?=$_SESSION['id']?>">Profil</a></li>
				<li><a href="?page=logout">Logout</a></li>
				<?php } ?>
			</ul>
		</div>
	</div>
</nav> 