<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Forum</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<link rel="stylesheet" href="public/css/bootstrap.min.css" media="screen">
		<link rel="stylesheet" href="public/css/custom.min.css">
		<link rel="stylesheet" href="public/css/style.css">
		<link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>      
		<![endif]-->    
	</head>

<body>
	<?php require('controllers/menu.php'); ?>
	<div class="wrap">
		<?php require('controllers/header.php'); ?>
		<?php require('controllers/content.php'); ?>
	</div>
	<?php require('controllers/footer.php'); ?>

	<script src="public/js/jquery.js"></script>
	<script src="public/js/bootstrap.min.js"></script>    
	<script src="public/js/script.js"></script>
	
</body>
</html>